import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import { Toaster } from "react-hot-toast";
import AppShell from "./components/AppShell";
import { ConfigProvider, App } from "antd";
import { antdTheme, suppressAntdWarnings } from "../lib/antd-theme";
import AntdWarningBoundary from "../lib/error-boundary";
import "../lib/suppress-warnings"; 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Suppress Ant Design warnings
  suppressAntdWarnings();

  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <AntdWarningBoundary>
          <ConfigProvider theme={antdTheme}>
            <App>
              <AppShell>
                {children}
              </AppShell>
              <Toaster position="top-right" />
            </App>
          </ConfigProvider>
        </AntdWarningBoundary>
      </body>
    </html>
  );
}
